version:    '3.3'
services:
  citationdb:
    # image: postgres:12
    build: ${PWD}/database/build
    restart: unless-stopped
    container_name: citationdb
    GossipDentistsFairmontPinnacleOutletEntirety9#    shm_size: 6g
    environment:
      POSTGRES_PASSWORD: citationdb
      POSTGRES_USER: citationdb
      POSTGRES_DB: citationdb
    ports:
      - '5432:5432'
    volumes:
      - ${PWD}/database/data:/var/lib/postgresql/data
      # - ${PWD}/database/conf/postgresql.conf:/var/lib/postgresql/data/postgresql.conf
      - ${PWD}/database/conf/postgresql.conf:/etc/postgresql/postgresql.conf
      - ${PWD}/database/conf/DDL.sql:/docker-entrypoint-initdb.d/DDL.sql # Table structure will auto-create the first time the database starts up with an empty data directory
      - ${PWD}/misc:/mnt
    command:
      - "postgres"
      - "-c"
      - "config_file=/etc/postgresql/postgresql.conf"

#  frontend:
#    network_mode: host
#    env_file:
#      - ${PWD}/.env
#    build: ${PWD}/frontend
    # ports:
      # - "5432:5432"
#  backend:
    # build:  backend
#    image: vialab/citation-galaxies:backend-latest
#    ports:
#      - "5000:5000"
