version:    '3.3'
services:
  citationdb:
    # image: postgres:12
    build: ${PWD}/database
    restart: unless-stopped
    container_name: citationdb
    stop_grace_period: "30s"
    environment:
      POSTGRES_PASSWORD: citationdb
      POSTGRES_USER: citationdb
      POSTGRES_DB: citationdb
    ports:
      - '5435:5432'
    volumes:
      # - ../citationdb-data:/var/lib/postgresql/data
      - /scratch/nbeals/work2/citationdb-data:/var/lib/postgresql/data
      # - ${PWD}/database/data:/var/lib/postgresql/data
      # - ../citationdb-data-old:/var/lib/postgresql/data
      # - ../citationdb-data-004:/var/lib/postgresql/data
      # - ../citationdb-data-citeonly-fast:/var/lib/postgresql/data
      # - ${PWD}/database/conf/postgresql.conf:/var/lib/postgresql/data/postgresql.conf
      # - ${PWD}/database/conf/postgresql.conf:/etc/postgresql/postgresql.conf
      - ${PWD}/config/postgresql.conf:/etc/postgresql/postgresql.conf
      # - ${PWD}/database/conf/DDL.sql:/docker-entrypoint-initdb.d/DDL.sql # Table structure will auto-create the first time the database starts up with an empty data directory
      # - ${PWD}/misc:/mnt
      - /etc/localtime:/etc/localtime:ro
      - ./sockets:/run/postgresql/
    command:
      - "postgres"
      - "-c"
      - "config_file=/etc/postgresql/postgresql.conf"

volumes:
  citationdb-data:
#  frontend:
#    network_mode: host
#    env_file:
#      - ${PWD}/.env
#    build: ${PWD}/frontend
    # ports:
      # - "5432:5432"
#  backend:
    # build:  backend
#    image: vialab/citation-galaxies:backend-latest
#    ports:
#      - "5000:5000"
